version: "3.8"
services:
  tfaas-engine:
    image: zjia/nightcore:asplos-ae
    hostname: faas-engine-{{.Task.Slot}}
    entrypoint:
      - /nightcore/engine
      - --gateway_addr=tfaas-gateway
      - --root_path_for_ipc=/tmp/nightcore/ipc
      - --func_config_file=/tmp/nightcore/func_config.json
      - --num_io_workers=4
      - --gateway_conn_per_worker=32
      - --disable_monitor
      - --instant_rps_p_norm=0.8
    depends_on:
      - tfaas-gateway
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /sys/fs/cgroup:/tmp/root_cgroupfs
    environment:
      - FAAS_CGROUP_FS_ROOT=/tmp/root_cgroupfs

  tfaas-gateway:
    image: zjia/nightcore:asplos-ae
    ports:
      - 8080:8080
    entrypoint:
      - /nightcore/gateway
      - --listen_addr=0.0.0.0
      - --http_port=8080
      - --func_config_file=/tmp/nightcore/func_config.json
      - --num_io_workers=8
      - --lb_per_fn_round_robin
      - --max_running_requests=0
    volumes:
      - /tmp/func_config.json:/tmp/nightcore/func_config.json

  etcd:
    image: bitnami/etcd:3.5
    hostname: etcd
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
    restart: always
  
  cacheserver:
    image: lechou/cacheserver:v2.50.1
    hostname: cacheserver-{{.Task.Slot}}
    entrypoint: ["./main"]
    volumes:
      - /mnt/inmem/requests:/requests
    environment:
      - ETCD_URI=etcd:2379
      - POD_IP=cacheserver-{{.Task.Slot}}
    depends_on:
      - middleshim

  middleshim:
    image: lechou/middleshim:v2.50.1
    hostname: middleshim-{{.Task.Slot}}
    entrypoint: ["./main"]
    environment:
      - ETCD_URI=etcd:2379
      - POD_IP=middleshim-{{.Task.Slot}}
      - caches=cacheserver-1,cacheserver-2,cacheserver-3,cacheserver-4,cacheserver-5,cacheserver-6,cacheserver-7,cacheserver-8
    depends_on:
      - etcd
  
  tfaas-test:
    image: lechou/of:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "of", "1"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver
  
  tfaas-deleteworkflow:
    image: lechou/of:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "of", "2"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver
  
  tfaas-registerworkflow:
    image: lechou/of:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "of", "3"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver

  tfaas-listCoursesworkflow:
    image: lechou/of:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "of", "4"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver
  
  tfaas-resetworkflow:
    image: lechou/of:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "of", "5"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver
  
  tfaas-delete:
    image: lechou/ef:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "ef", "6"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver

  tfaas-register:
    image: lechou/ef:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "ef", "7"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver
  
  tfaas-isDelete:
    image: lechou/ef:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "ef", "8"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver

  tfaas-isRegister:
    image: lechou/ef:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "ef", "9"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver

  tfaas-listCourses:
    image: lechou/ef:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "ef", "10"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver

  tfaas-resetCourse:
    image: lechou/ef:v2.50.1
    entrypoint: ["/tmp/nightcore/run_launcher", "ef", "11"]
    volumes:
      - /mnt/inmem/tfaas:/tmp/nightcore
      - /mnt/inmem/requests:/requests
    environment:
      - FAAS_GO_MAX_PROC_FACTOR=4
      - GOGC=200
    depends_on:
      - cacheserver
